### ISSUE TITLE
Add bill of materials and assembly instructions

### ISSUE THREAD

**Issue by jonnew** [open-ephys/commutator-docs#11]
We should add a BOM and assembly instructions for both variants. It should assume that the PCB has already been assembled.

**Comment by jonnew** [comment]
Actually, just link the BOM: https://docs.google.com/spreadsheets/d/1M2R0Q2-OuRHzctt05BxtA3hxNcCHtRZHORzCKElmG1Q/edit#gid=1283420334

but assembly instructions would be good.

**Comment by cjsha** [comment]
Attempted fix with commit [ede20a5](https://github.com/open-ephys/commutator-docs/commit/ede20a55e4b3b6ba9487136ccc25961c6d8f0540)

**Comment by jonnew** [comment]
Edited a bit. I think we are good here.
