### ISSUE TITLE
Add acquisition system to section titles and intros within "Automating Commutation" 

### ISSUE THREAD

**Issue by ChucklesOnGitHub** [open-ephys/commutator-docs#2]
![image](https://user-images.githubusercontent.com/16124331/229486211-80a32bd0-15a5-42d4-8582-5d8b776361cd.png)

It would be useful at this menu level to know for what acq system each guide is, besides the source of orientation data and acquisition software.
e.g. "Automate Commutation with Bonsai and UCLA Miniscope v4" could be ONIX or Miniscope DAQ

Since the ONIX docs already have the commutator section, maybe the decision here is to either
a) Link from commutator docs to onix docs -> then add this link to current commutator docs
b) Link from onix docs to commutator docs -> move sections from onix docs to commutator docs and add link to onix docs

**Comment by jonnew** [comment]
I want to move the commutator docs from ONIX into this docs website. I plan to just turn that page into a links into the commutator docs.

**Comment by cjsha** [comment]
It sounds like Jon is going with option b presented by Ceci. 

I agree, the user's acquisition hardware is arguably more important than the software. Is something like "Automate Commutation with Onix and UCLA Miniscope v4" more adequate then? And then I can break it down by software (Bonsai or Miniscope-DAQ-QT-GUI) on the page with that label?

**Comment by jonnew** [comment]
Whatever the solution is, I think the top of each page should have  picture of the relevant hardware. e.g. a daq and miniscope, a breakout and miniscope, breakout and hs-64, etc.

**Comment by ChucklesOnGitHub** [comment]
yes Cris, I think it might easier to find things that way
1: I have this acq hardware (when the SPI commutator comes, there will be additional ones)
2: I have this headstage
3: I want to use this software

**Comment by ChucklesOnGitHub** [comment]
yep, that's what I meant, i think it would work

**Comment by cjsha** [comment]
I addressed this issue in the recent commit/push. Please check it out and let me know what you think

**Comment by ChucklesOnGitHub** [comment]
This is super clear, awesome!

**Comment by ChucklesOnGitHub** [comment]
A note: I think when we get to the stage of populating the section "[ONIX and Computer Vision"](https://open-ephys.github.io/commutator-docs/coax-commutator/user-guide/automatic-control/onix-computervision.html), it will actually be applicable to computer vision with commutators in general, and not tied to a particular acquisition system. I sugges figuring it out when that time comes.

**Comment by cjsha** [comment]
I think for this particular case when the entire page is identical for spi commutator and and coax commutator, I think we make one file that the coax commutator doc and the spi commutator doc each pulls from using the  `..include::` directive
