### ISSUE TITLE
Add automate commutation with Bonsai and UCLA Miniscope v4 for the ONIX system

### ISSUE THREAD

**Issue by ChucklesOnGitHub** [open-ephys/commutator-docs#3]
Either in the commutator docs or in the ONIX docs, see related #2

**Comment by jonnew** [comment]
There are a couple TODOs, but is this what you are looking for: https://open-ephys.github.io/commutator-docs/coax-commutator/user-guide/automatic-control/bonsai-miniscope.html

**Comment by cjsha** [comment]
Is the difference that miniscope workflow on that webpage linked by jon uses the miniscope daq instead of onix?

**Comment by ChucklesOnGitHub** [comment]
yes, the docs on how to use miniscope with ONIX don't exist afaik

**Comment by ChucklesOnGitHub** [comment]
actually, what doesn't exist is an explicit example workflow. the docs are [here](https://open-ephys.github.io/onix-docs/Software%20Guide/Bonsai.ONIX/Nodes/MiniscopeV4Device.html#bonsai-miniscopev4dev)

**Comment by cjsha** [comment]
I notice that workflow has a node for BNO055 and writing quarternions to a csv - but no actual commutation occurring right? I can't actually open this file so I can't look into the details or modify to write any JSON commands to the commutator. How do I move forward with this? I wouldn't mind remoting into a computer if someone can help me test.

Sidenote: what other coax hardware do we plan to commutate? Aaron mentioned Neuropixels once. Can we open separate issues for those as well? Thanks
