### ISSUE TITLE
Add automate commutation subsection: ONIX and Neuropixels-1.0 Headstage

### ISSUE THREAD

**Issue by ChucklesOnGitHub** [open-ephys/commutator-docs#6]
The dual npix-1.0 is is the only other headstage we currently have with an IMU that is not explicitly mentioned in the commutator docs
https://open-ephys.github.io/onix-docs/Hardware%20Guide/Headstages/headstage-neuropix.html

**Comment by cjsha** [comment]
Is it the same workflow as the headstage64? If so, should I put them on the same webpage? Title would be something like:
**Onix and Coaxial Headstage64 or NeuroPixels 1.0**
