### ISSUE TITLE
Validate Commutator Workflows

### ISSUE THREAD

**Issue by cjsha** [open-ephys/commutator-docs#7]
Since I won't have hardware in-hand until as late as June in the worst case, I'm wondering if someone can help validate all the workflows  in the _automate_ section of the docs. @jonnew @ChucklesOnGitHub Can either of you assign the appropriate people to this task? Thanks

**Comment by jonnew** [comment]
The computer vision workflow was validated yesterday. The rest have been validated in the field already. I think we can close this.
