### ISSUE TITLE
Corrections to labelled connections image

### ISSUE THREAD

**Issue by jonnew** [open-ephys/commutator-docs#8]
In this image

https://github.com/open-ephys/commutator-docs/blob/2dc6c1bdf65be911070aba4adbf997da157851ff/source/_static/images/connections-numbered.png

- The connection "2. SMA Connector (PCIe Host)" should be "2. SMA Connector (to ONIX host, Miniscope DAQ, etc)"
- Can you add the editable version of this file to the repo?

**Comment by cjsha** [comment]
I think is fixed now with commit [37d3d1d](https://github.com/open-ephys/commutator-docs/commit/37d3d1d9d44fee697875c1889afd46e1bdc68c0d)
