### ISSUE TITLE
More extensive documentation on tether managment

### ISSUE THREAD

**Issue by jonnew** [open-ephys/commutator-docs#9]
This attention block needs to be expanded:

https://github.com/open-ephys/commutator-docs/blob/f6260f987d45663788451961b4d3d215d2e7c578/source/coax-commutator/user-guide/mount-connect.rst?plain=1#L87

- We need a guide on how to use the hook and elastic thread to keep the tether away from the animal.
-  Diagrams and pictures would be useful for this.

**Comment by cjsha** [comment]
Attempted fix with commit 5cd8aba

**Comment by jonnew** [comment]
Just closed, but realized I have not gotten a part number for the elastic thread yet.

**Comment by jonnew** [comment]
Here is the part number for the elastic thread:

Clover 3158

https://theknittersattic.co.uk/product/elastic-yarn-thread-black/

@cjsha please add this and feel free to close afterwards.

**Comment by cjsha** [comment]
A new issue was created #20 with a bit more details. I'm closing this one and I'll do a PR for #20.
